feat: 스터디 카페 등록
f-lab-edu/Brothers-of-Study pull request #44
Opened 2021-12-06 01:40 UTC by jinukix

~~~json
{
    "title" : "스터디 카페 이름",
    "address":"스터디 카페 주소",
    "rooms": [
        {
            "number": 1,
            "capacity": 2
        },
        {
            "number": 2,
            "capacity": 1
        },
        {
            "number": 3,
            "capacity":1
        }
    ]
}
~~~
스터디 카페 등록은 위와 같은 json을 받아 처리하게됩니다.
만약 중복되는 방 번호가 있는 경우 DuplicatedRoomNumberException 예외가 발생하게 됩니다.

2021-12-08 15:17 UTC, f-lab-joseph requested changes

2021-12-08 15:17 UTC, f-lab-joseph commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +            set.add(number);
로직이 좀 이상합니다. 좀 더 효율적인 방법은 없나요 ?

2021-12-08 15:17 UTC, f-lab-joseph commented on src/main/java/kr/bos/service/StudyCafeService.java
> +        roomMapper.insertRooms(studyCafeDto);
스터디카페를 만든 이후에는 방 정보를 업데이트 하는 것이 불가능한가요 ?

2021-12-09 01:55 UTC, jinukix commented on src/main/java/kr/bos/service/StudyCafeService.java
> +        roomMapper.insertRooms(studyCafeDto);
방 추가, 삭제, 수정 기능을 이슈항목에 추가해두었습니다.

2021-12-09 01:55 UTC, jinukix commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +            set.add(number);
스트림을 사용하는 방식으로 변경하겠습니다.
~~~java
        if (list.size() != list.stream().distinct().count()) {
            throw new DuplicatedRoomNumberException();
        }
~~~

2021-12-09 14:39 UTC, f-lab-joseph commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +            set.add(number);
dto 가 데이터 표현, 밸리데이션만을 담당하는 것이 아니고 여기저기서 DTO 의 값들을 수정하게 되면 의도치 않은 사이드 이펙트가 어느순간 발생할 것 같은데 더 좋은 방법이 없을까요 ?

한번 생각해보시고, 다른 샘플/예제 프로젝트에선 어떻게 하는지 찾아보시면 좋을 것 같습니다.
일단 approve 처리는 할게요.

2021-12-09 14:39 UTC, f-lab-joseph approved these changes

2021-12-09 21:01 UTC, jinukix commented
DTO는 계층간 데이터 교환, 도메인 객체만이 DB 작업에 사용하도록 수정했습니다. Dto -> 도메인간의 변환 위치는 서비스 레이어에서 이루어질것같습니다.

2021-12-10 08:05 UTC, f-lab-joseph commented
force push 는 가능하면 자제해주세요 (REBASE 를 하지 않았다면)

2021-12-11 17:24 UTC, merged