feat: 리뷰 CRUD
f-lab-edu/Brothers-of-Study pull request #46
Opened 2021-12-06 08:51 UTC by jinukix

리뷰 목록 조회, 작성, 업데이트, 삭제 기능 구현했습니다.

- testcontainers 관련 의존성들은 필요없을거 같아 모두 삭제했습니다.
- @BlackCheck 블랙리스트 체크 어노테이션은 스터디 카페 등록 PR에서 구현했습니다. 
- mysql 에서는 UPDATE, DELETE 할 때 자기 테이블을 서브쿼리로 못 사용하더라구요. 
찾아보니 서브쿼리를 한번더 감싸면 된다고 해서 다음과 같이 구현했습니다.
~~~sql
    DELETE FROM reviews
    WHERE id =
    (
    SELECT id FROM
    ( SELECT id FROM reviews WHERE id = #{reviewId} AND user_id = #{userId} ) sub_query
    )
~~~

2021-12-08 15:11 UTC, f-lab-joseph requested changes

2021-12-08 15:11 UTC, f-lab-joseph commented on build.gradle
> +    implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:1.4.1'
왜필요한가요 ?

2021-12-08 15:11 UTC, f-lab-joseph commented on src/main/java/kr/bos/dto/request/ReviewRequest.java
> +    @NotBlank
위쪽에 userId, studyCafeId 는 없어도 되는건가요 ? 여기만 밸리데이션이 있는데 궁금합니다.

2021-12-08 15:11 UTC, f-lab-joseph commented on src/main/java/kr/bos/mapper/ReviewMapper.java
> +    int updateReview(Map<String, Object> map);
다른쪽에는 전용 객체를 사용하시는데 이쪽에서만 맵을 사용하시는 것은 적절하지 않아보입니다. 
업데이트를 위한 DTO 를 만드는 것이 좋지 않을까요 ?

2021-12-08 15:11 UTC, f-lab-joseph commented on src/main/java/kr/bos/service/ReviewService.java
> +        reviewRequest.setStudyCafeId(studyCafeId);
요청할때 사용한 DTO 에 추가적으로 값을 세팅하는 것은 적절하지 않아보입니다만 .. 
다른 방법으로 insert 를 할 수 없을까요 ?

2021-12-08 15:11 UTC, f-lab-joseph commented on src/test/java/kr/bos/service/ReviewServiceTest.java
> +    @DisplayName("리뷰 목록 조회에 성공합니다.")
조회 시 데이터가 없는 경우는 없나요 ?

2021-12-09 02:19 UTC, jinukix commented on build.gradle
> +    implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:1.4.1'
페이지네이션을 처리하는 라이브러리입니다. 해당 라이브러리를 통해 다음과 같이 편하게 페이제이션 처리를 할 수 있습니다.

~~~java
    public PageInfo<ReviewResponse> getReviews(@CurrentUserId Long userId,
        @PathVariable("studyCafeId") Long studyCafeId, @RequestParam("page") Integer page,
        @RequestParam("size") Integer size) {
        PageHelper.startPage(page, size);
        return PageInfo.of(reviewService.getReviews(studyCafeId));
    }
~~~

2021-12-09 02:28 UTC, jinukix commented on src/test/java/kr/bos/service/ReviewServiceTest.java
> +    @DisplayName("리뷰 목록 조회에 성공합니다.")
조회시 데이터가 없을 수도 있습니다. 다른 처리나, 예외가 발생하지 않고, 0을 조회한 것에 가깝다고 생각해 데이터가 없는 경우를 다른 경우의 수라고 생각하지 않았습니다.

2021-12-09 02:59 UTC, jinukix commented on src/main/java/kr/bos/dto/request/ReviewRequest.java
> +    @NotBlank
userId, studyCafeId는 제거했습니다.

2021-12-09 03:01 UTC, jinukix commented on src/main/java/kr/bos/service/ReviewService.java
> +        reviewRequest.setStudyCafeId(studyCafeId);
reviewRequest 에 userId, studyCafeId 멤버를 제거했습니다. 다음과 같이 파라미터로 모두 넘겨 처리하는것으로 변경하겠습니다
~~~java
void insertReview(@Param("reviewRequest") ReviewRequest reviewRequest,
        @Param("userId") Long userId,
        @Param("reviewId") Long reviewId);
~~~

2021-12-09 03:02 UTC, jinukix commented on src/main/java/kr/bos/mapper/ReviewMapper.java
> +    int updateReview(Map<String, Object> map);
Map을 사용하지 않고 필요한 값들을 전부 파라미터로 넘겨 처리하는 방식으로 변경했습니다.
~~~java
    int updateReview(@Param("reviewRequest") ReviewRequest reviewRequest,
        @Param("userId") Long userId,
        @Param("reviewId") Long reviewId);
~~~

2021-12-11 17:42 UTC, jinukix commented
작업을하다가 꼬인부분이 있어 커밋 reset 하다보니 force push가 일어났습니다. 주의하겠습니다.
수정 사항은 모델 객체를 domain, request, response로 구분하는 작업을 진행했습니다

2021-12-12 08:42 UTC, f-lab-joseph approved these changes

2021-12-12 08:43 UTC, f-lab-joseph commented
도메인 객체는 어디 분리돼있나요 ?

2021-12-12 11:17 UTC, jinukix commented
로컬에서 커밋만해두고 푸시를 빠트렸네요 ㅠ. 다시 확인해서 반영했습니다

2021-12-13 13:25 UTC, merged