feat: 예약 하기.
f-lab-edu/Brothers-of-Study pull request #47
Opened 2021-12-06 10:28 UTC by jinukix

~~~json
{
    "startTime" : "2021-11-28 09:10",
    "endTime": "2021-11-28 09:31"
}
~~~
예약하기는 위와 같은 json을 받아 처리합니다.
시간은 분 단위 까지로 받게되며 시작 시간이 완료 시간보다 뒤에있을 경우, 총 이용시간이 10분 이내인 경우 예외가 발생합니다.

- testcontainers 관련 의존성들은 필요없을거 같아 모두 삭제했습니다.
- @BlackCheck 블랙리스트 체크 어노테이션은 스터디 카페 등록 PR에서 구현했습니다.

2021-12-08 11:01 UTC, f-lab-joseph commented
blackcheck 유저가 멘션됐네요

2021-12-08 11:04 UTC, f-lab-joseph requested changes

2021-12-08 11:04 UTC, f-lab-joseph commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0'
이건 왜필요한가요 ?

2021-12-08 11:04 UTC, f-lab-joseph commented on build.gradle
> +    implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:1.4.1'
어떤 역할을 하는 라이브러린가요 ?

2021-12-08 11:04 UTC, f-lab-joseph commented on src/test/java/kr/bos/service/ReservationServiceTest.java
> +        assertEquals(reservationRequest.getRoomId(), 2L);
테스트가 좀 이상한데요, 테스트를 위해서 위 코드에서 REQUEST DTO 에 값을 설정하고 있던건가요 ?

2021-12-08 13:24 UTC, jinukix commented on build.gradle
> +    implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:1.4.1'
해당 라이브러리는 리뷰 목록 조회를 위해 등록한 라이브러리인데 여기 브랜치에 딸려온거같습니다. 페이지네이션을 처리하는 라이브러리입니다. 해당 라이브러리를 통해 다음과 같이 편하게 페이제이션 처리를 할 수 있습니다.

~~~java
    public PageInfo<ReviewResponse> getReviews(@CurrentUserId Long userId,
        @PathVariable("studyCafeId") Long studyCafeId, @RequestParam("page") Integer page,
        @RequestParam("size") Integer size) {
        PageHelper.startPage(page, size);
        return PageInfo.of(reviewService.getReviews(studyCafeId));
    }
~~~

2021-12-08 13:25 UTC, jinukix commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0'
문자열로 받은 값을 LocalDateTime 으로 포맷하기 위해 사용했습니다.
~~~java
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm",
        timezone = "Asia/Seoul")
    LocalDateTime startTime;
~~~

2021-12-08 13:28 UTC, jinukix commented on src/test/java/kr/bos/service/ReservationServiceTest.java
> +        assertEquals(reservationRequest.getRoomId(), 2L);
createReservation 메소드에서 requestDto에 setUserId, setRoomId가 정상적이게 실행됬는지를 테스트했습니다.

~~~java
    public void createReservation(ReservationRequest reservationsRequest, Long userId,
        Long roomId) {
        ...

        reservationsRequest.setUserId(userId);
        reservationsRequest.setRoomId(roomId);
        reservationMapper.insertReservation(reservationsRequest);
    }
~~~

2021-12-09 14:46 UTC, f-lab-joseph commented on src/test/java/kr/bos/service/ReservationServiceTest.java
> +        assertEquals(reservationRequest.getRoomId(), 2L);
DTO 계층을 바로 SQL 작업에 사용하고 있는데 별도의 도메인 계층을 만드는 것은 고려하지 않으시나요 ?

2021-12-09 17:47 UTC, jinukix commented on src/test/java/kr/bos/service/ReservationServiceTest.java
> +        assertEquals(reservationRequest.getRoomId(), 2L);
DTO에 대한 개념 이해가 부족했던거 같습니다. DTO는 계층간 데이터 교환에만 사용하도록 하겠습니다.
model 객체들을 만들어 db 작업은 model 객체를 통해서 처리하는것으로 변경하겠습니다. 
전체적으로 수정이 필요할것 같네요.

2021-12-10 14:36 UTC, f-lab-joseph commented on src/main/java/kr/bos/model/Reservation.java
> +    Long userId;
access modifier를 default 로 지정한 이유가 있을까요?

2021-12-10 14:46 UTC, jinukix commented on src/main/java/kr/bos/model/Reservation.java
> +    Long userId;
실수인거같습니다.. private로 수정하겠습니다.

2021-12-12 08:41 UTC, f-lab-joseph approved these changes

2021-12-12 08:41 UTC, f-lab-joseph commented on src/main/java/kr/bos/controller/StudyCafeController.java
> +        reservationService.createReservation(reservationsRequest, userId, roomId);
개인적으로 DTO를 서비스 Layer로 내리기 보다는 도메인 객체로 변환하거나, 필요한 파라미터를 내려주는게 좋은 것 같습니다. Layer간의 경계를 넘는 것 같아요.

2021-12-13 13:17 UTC, merged