Feature: study cafe list
f-lab-edu/Brothers-of-Study pull request #56
Opened 2021-12-16 03:14 UTC by SangHoonly

2021-12-16 05:59 UTC, jinukix requested changes
저는 서비스 레이어에만 존재하는 기능들은 좋은 형태라고 생각하지 않습니다. 메인 브랜치에는 현재 사용할 수 있는 완성된 기능들만 존재하는 것이 옳아보입니다. 사용할 수 있도록 만들어주던가, 다른 브랜치로 빼놓으시는게 좋을거같습니다. 혹시 다른 생각이 있으시면 말씀해주세요!

2021-12-16 05:59 UTC, jinukix commented on jacoco.gradle
> +        '**/exception',
예외에 대한 테스트 작성은 필요할것같습니다.

2021-12-16 05:59 UTC, jinukix commented on src/main/java/kr/bos/controller/StudyCafeController.java
> +    }
그리고 해당 서비스를 이용하기 전에 검증 작업이 필요할 것 같은데 제가 작성해둔 AOP 어노테이션도 한번 고려해보시면 좋을거같습니다. 엔드포인트 형식도 통일되어야할것같습니다. 그리고 응답 코드도 필요할것 같습니다.

2021-12-16 05:59 UTC, jinukix commented on src/main/java/kr/bos/domain/StudyCafe.java
> +public class StudyCafe {
이미 작성되어있는 domain 클래스가 있는데 추가적으로 생성하신 이유가 있을까요?
도메인 클래스에서 Setter는 최대한 사용하지 않는 것이 좋을거같습니다.

2021-12-16 05:59 UTC, jinukix commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +    private Long id;
마찬가지로 이미 생성되어 있는 DTO 객체가 존재합니다. 
저는 요청, 응답 객체에 사용하는 데이터가 다르기 때문에 요청, 응답 DTO를 분리하는 것이 좋다고 생각합니다. 

저희 스터디 카페 리스트 응답 데이터로는 스터디 카페 테이블 데이터 외에도 리뷰 평균 점수, 북마크 여부, 현재 빈 방의 개수가 들어가야할거같습니다. 요청에 보내야될 데이터, 응답에 받아야하는 데이터를 한번 생각해보시고 생각 말씀해주시면 좋을거같습니다. 이후 구현하실 생각이시라면 이슈를 남겨주시면 좋을거같네요. 아 그리고 페이지네이션, 필터, 정렬 기능도 마찬가지로 이후 구현 예정이라면 이슈를 남겨주세요.

2021-12-16 05:59 UTC, jinukix commented on src/main/java/kr/bos/exception/StudyCafeNotFoundException.java
> +public class StudyCafeNotFoundException extends RuntimeException {
예외처리에대한 응답 코드도 들어가면 좋을거같아요.

2021-12-16 05:59 UTC, jinukix commented on src/main/resources/application.yml
> +    mapper-locations: classpath:/mapper/**/*.xml
뭔가 잘못들어 간거같네요. MyBatis 설정은 mybatis-config.xml 파일로 따로 분리했습니다. config 쪽 확인해보시는게 좋을거같습니다.

2021-12-16 05:59 UTC, jinukix commented on src/main/resources/mapper/StudyCafeMapper.xml
> +    WHERE id=#{id}
제가 작성한 DDL 확인해보시면 created_at, updated_at은 생성, 수정이 될때 자동으로 값이 들어가게 설정되어있습니다.

2021-12-16 06:13 UTC, jinukix commented
아 그리고 git action이 실행되질 않았네요. 메인에 요청할때마다 ./gradlew clean build 이 실행되게 걸어놓았는데.. 저번 PR에서는 정상적으로 동작했는데 혹시 짐작가시는 부분이 있을까요??

2021-12-16 06:17 UTC, f-lab-joseph commented on src/main/java/kr/bos/controller/StudyCafeController.java
> +    }
200으로 내려가도 문제 없을 것 같긴한데요 ㅎ 다른 어떤 응답코드가 필요할까요 ?

2021-12-16 06:18 UTC, f-lab-joseph commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +    private Long id;
요청/응답은 분리해주는 것이 좋을 것 같습니다.

2021-12-16 07:05 UTC, jinukix commented on src/main/java/kr/bos/controller/StudyCafeController.java
> +    }
지정하지않으면 200으로 내려가는군요. 제가 몰랐던 부분이였네요. 감사합니다.

2021-12-17 08:23 UTC, SangHoonly commented on src/main/java/kr/bos/dto/StudyCafeDto.java
> +    private Long id;
음 요청에 보내야 할 데이터는 스터디 카페 이름이면 될 것 같고(스터디 카페 이름을 입력하여 검색하므로), 응답 데이터는 리뷰 평균 점수, 북마크 여부, 빈 방 개수가 포함되어야 할 것 같습니다. 
요청 응답 분리한 후 추가 구현 하겠습니다~

2021-12-17 08:24 UTC, SangHoonly commented
음 git action이 적용되지 않는 것은 저도 잘 모르겠네요... 다시 한번 확인해 볼게요!

2021-12-17 20:49 UTC, jinukix approved these changes

2021-12-19 10:52 UTC, f-lab-joseph commented
리뷰단계 끝나셨다면 conflict 해결후 머지해주세요ㅕ.

2021-12-20 06:56 UTC, merged