feat: 방 추가하기, 수정하기.
f-lab-edu/Brothers-of-Study pull request #58
Opened 2021-12-21 19:32 UTC by jinukix

- 방 추가하기, 수정하기 기능 추가. 
- 방 번호 중복 처리는 db단에서 unique key로 처리.
- DDL 수정 (외래키 제거 및 unique key 추가, 인덱스 설정은 이후에 예정)

2021-12-24 09:23 UTC, f-lab-joseph approved these changes

2021-12-24 09:23 UTC, f-lab-joseph commented on src/main/java/kr/bos/service/RoomService.java
> +            throw new DuplicatedRoomNumberException();
에러 발생 시 로깅은 꼭 해주세요. 추후 운영성 업무 대응 시 로그없이 추적이 불가합니다.

2021-12-26 18:12 UTC, jinukix commented on src/main/java/kr/bos/service/RoomService.java
> +            throw new DuplicatedRoomNumberException();
해당 예외는 데이터베이스에서 중복된 유니크 컬럼이 들어왓을 때 발생하는 에러입니다.
예측하고 있던 예외에도 로깅을 거는 것이 좋을까요?

![스크린샷 2021-12-25 오후 7 18 56](https://user-images.githubusercontent.com/74256905/147416590-21e1944e-2f95-4581-bc74-ccb9333a795e.png)

해당 이미지의 위는 실제 에러 메시지입니다.
아래는 기존에 출력되는 로그 메시지입니다.

기존에 출력되는 로그 메시지보다 조금 더 디테일한 에러 메시지를 남기는 것이 좋을까요?? 한편으로는 작성해둔 예외의 메시지와 409 에러 코드로도 대응할 수 있지 않을까라는 생각도 듭니다.

2021-12-27 06:51 UTC, SangHoonly approved these changes

2021-12-28 08:15 UTC, f-lab-joseph requested changes

2021-12-28 08:15 UTC, f-lab-joseph commented on src/main/java/kr/bos/service/RoomService.java
> +            throw new DuplicatedRoomNumberException();
로그 레벨이 error 가 아니더라도 로깅은 가능합니다. 
예측하고 있던 예외에도 사용자 입장에서는 이해하기 어려운 동작일 수 있고, 이에 따른 cs 등의 요청 처리를 위해서는 코드흐름의 로깅이 꼭 필요합니다. (에러 context 에 대한 데이터도 로깅에 포함돼야겠죠)

또한 협업한다고 생각했을때, 협업자에게는 지금 말씀하신 오류 처리 흐름이(내부 코드에서 exception 을 throw 한것이 아닌 코드외 영역에서의 exception 처리) 당연한 것이 아니기 때문에 에러를 던지고, 로깅 없이 처리한다는 것은 권해드리기 어려운 방식 같네요.

2021-12-28 08:15 UTC, f-lab-joseph commented on src/main/java/kr/bos/service/RoomService.java
> +            throw new DuplicatedRoomNumberException();
이펙티브 자바의 예외를 무시하지 말라는 챕터를 참고하시면 좋을 것 같습니다.

2021-12-28 20:09 UTC, jinukix commented
발생하는 에러는 방을 추가했을 때 중복된 방인 경우 MySQL 에서 설정한 Unique key로 인해 발생하는 에러입니다.
Unique key를 사용한 이유는 Service 레이어에서 중복 검증 로직을 작성하지 않아도 되고, 데이터의 무결성을 지키기 위함입니다.
하지만 그로 인해 중복된 방을 삽입했을 경우 필연적으로 예외가 발생하게 됩니다.

이팩티브 자바에서 "예외는 진짜 예외인 상황에서만 사용하라"는 내용을 보고 고민끝에 예외를 발생시키지 않고 처리하는 방식으로 수정하기로 했습니다. 따라서 INSERT 전에 추가적으로 검증 로직을 삽입했습니다.

검증 로직에 명시적인 LOCK은 사용하지 않았습니다. UNIQUE KEY로 인해 중복 요청에 대한 제어는 할 수 있을거라 생각합니다.

2022-01-09 02:40 UTC, f-lab-joseph approved these changes

2022-01-12 23:25 UTC, merged