스터디 카페 리스트 : 정렬 기능, 필터링 기능 추가
f-lab-edu/Brothers-of-Study pull request #63
Opened 2021-12-23 16:43 UTC by SangHoonly

이미 구현되어 있는 findStudyCafesByKeyword 함수를 통해, 스터디 카페 목록을 가져올 수 있습니다.
필터링과 정렬을 어떻게 구현하느냐가 관건이었는데, 사실은 백엔드 측에서 스터디 카페 목록을 그냥 긁어와서 프론트에 json으로 쏴 주기만 하고
프론트 측에서 버튼 핸들러 함수를 통해 가져온 데이터들을 필터링 / 정렬하는 것이 깔끔하다고 생각했습니다. 사용자가 필터링 / 정렬을 수십 번 하더라도 결국 DB i/o는 1번이면 충분하니깐요. 허나 지금은 필터링 / 정렬 등의 기능들의 구현을 경험해보고 싶어서 필터링된 / 정렬된 데이터들을 데이터로 쏴 주는 것을 목표로 삼았습니다.
한가지 짚고 넘어가야하는 것이, 정렬 기준 중 '이용횟수순'이 있습니다. 테이블을 설계할 때 어디에도 넣지 않았던 값이죠. 이 값을 어디서, 어떻게 가져와야 하는지 현재 계속 고민중입니다. 일단은 임시방편으로 단지 StudyCafeRes 객체에 필드로 넣어서 때우긴 했지만, 해결책을 찾아서 추후에 수정할 계획입니다.

2021-12-23 18:09 UTC, jinukix commented
개인적인 생각입니다. 
저희는 대규모 서비스를 목표로 프로젝트를 진행하고 있습니다. 따라서 스터디 카페의 개수가 100만개 1000만개의 상황까지 고려해서 개발해야한다고 생각합니다. 그 많은 데이터를 프론트에서 처리하기에는 무리가 있어보입니다. DB I/O가 여러번 발생하더라도 필터/정렬/페이징마다 데이터베이스단에서 처리가 이루어져야한다고 생각합니다.

이용횟수는 초창기 ERD에서 스터디 카페 테이블에 존재하던 컬럼이였지만 정규화를 위해 제외했던 컬럼입니다. 값을 가지고 올 수 있을거라 생각합니다. 천천히 생각해보시면 좋을거같네요.

2021-12-28 08:06 UTC, f-lab-joseph commented
네 필터/정렬 등의 작업은 서버 내에서 구현해주시면 좋겠네요

2021-12-28 08:09 UTC, f-lab-joseph requested changes

2021-12-28 08:09 UTC, f-lab-joseph commented on src/main/java/kr/bos/utils/StudyCafeListFilter.java
> +        return filterMapper.get(filterKeyword);
필터 케이스에 대한 TC 가 없어서 필터가 정확히 어떻게 동작하는지 확인/이해가 어렵네요. 추가해주시면 좋겠습니다

2022-01-02 19:56 UTC, jinukix requested changes

2022-01-02 19:56 UTC, ukjjang commented on src/main/java/kr/bos/service/StudyCafeService.java
> +                .sorted(sortMapper.get(sortKeyword)).collect(Collectors.toList());
필터, 정렬은 데이터베이스에서 처리하는 것이 좋아보입니다.

2022-01-03 08:59 UTC, SangHoonly commented on src/main/java/kr/bos/service/StudyCafeService.java
> +                .sorted(sortMapper.get(sortKeyword)).collect(Collectors.toList());
필터/정렬 기능을 DB에서 처리하느냐 혹은 서버 로직으로 처리하느냐의 차이인 것 같은데, 사실 서버 로직으로 처리하여도 크게 문제가 되지 않는다고 생각되는게 일단 필터 기능은 "어디서 거르냐"의 차이로 사실 성능상에 큰 문제는 없어보이고 정렬 또한 n * log(n)의 로직을 db에서 수행하느냐 혹은 서버에서 수행하느냐의 차이인데 n은 고정이므로 log(n)의 성능 차이만 고려하면 됩니다. 사실 log(n) 성능 차이는 DB나 서버나 유의미할 정도가 아니라고 생각됩니다. 따라서, 만일 유의미한 차이가 발생할 경우 후에 DB에서 처리하도록 리펙토링을 해도 될 것 같습니다!

2022-01-03 14:16 UTC, ukjjang commented on src/main/java/kr/bos/service/StudyCafeService.java
> +                .sorted(sortMapper.get(sortKeyword)).collect(Collectors.toList());
성능상의 큰 문제가 있을거같습니다. 필터, 정렬은 서버에서 처리하냐, DB에서 처리하느냐는 큰 차이가 존재합니다. 만약 대규모의 데이터를 리스트에 담아서 사용하게 되면 OutOfMemory, 빈번한 GC로 인해 문제가 심각할거라 생각합니다. 그리고 DB에서 처리한다면 인덱스를 통해 좀 더 효율적으로 처리할 수 있지 않을까요? 그리고 모든 레코드를 가지고와야해 Blocking 발생도 자주 일어날 거 같습니다. 버퍼 풀의 데이터도 많이 올려놔야해 이것도 성능 문제로 이어질 수 있을거 같네요.

2022-01-13 05:16 UTC, closed without merging